USE [YOUR_DATABASE_NAME]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FINGERPRINTS.WEBRTCS](
	[Fingerprints.WEBRTC.ID] [int] IDENTITY(1,1) NOT NULL,
	[Fingerprints.WEBRTC.ipv4] [nvarchar](15) NOT NULL,
	[Fingerprints.WEBRTC.ipv6] [nvarchar](64) NOT NULL,
 CONSTRAINT [PK_FINGERPRINTS.WEBRTCS] PRIMARY KEY CLUSTERED 
(
	[Fingerprints.WEBRTC.ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


