USE [YOUR_DATABASE_NAME]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FINGERPRINTS.AUDIOS](
	[Fingerprint.Audio.ID] [int] IDENTITY(1,1) NOT NULL,
	[Fingerprint.Audio.sampleRate] [int] NOT NULL,
	[Fingerprint.Audio.outputLatency] [float] NOT NULL,
	[Fingerprint.Audio.maxChannelCount] [tinyint] NOT NULL,
 CONSTRAINT [PK_FINGERPRINTS.AUDIOS] PRIMARY KEY CLUSTERED 
(
	[Fingerprint.Audio.ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


