USE [YOUR_DATABASE_NAME]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FINGERPRINTS.OS.BROWSERS.VOICES](
	[Fingerprint.OS.Browser.ID] [int] NOT NULL,
	[Fingerprint.OS.Browser.Voice.ID] [int] IDENTITY(1,1) NOT NULL,
	[Fingerprint.OS.Browser.Voice] [nvarchar](max) NOT NULL,
	[Fingerprint.OS.Browser.Voice.blockIfNotDefined] [bit] NOT NULL,
	[Fingerprint.OS.Browser.fakeCompletion] [bit] NOT NULL,
	[Fingerprint.OS.Browser.charsPerSecond] [float] NOT NULL,
 CONSTRAINT [PK_FINGERPRINTS.OS.BROWSERS.VOICES] PRIMARY KEY CLUSTERED 
(
	[Fingerprint.OS.Browser.Voice.ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[FINGERPRINTS.OS.BROWSERS.VOICES]  WITH CHECK ADD  CONSTRAINT [FK_FINGERPRINTS.OS.BROWSERS.VOICES_FINGERPRINTS.OS.BROWSERS] FOREIGN KEY([Fingerprint.OS.Browser.ID])
REFERENCES [dbo].[FINGERPRINTS.OS.BROWSERS] ([Fingerprint.OS.Browser.ID])
GO

ALTER TABLE [dbo].[FINGERPRINTS.OS.BROWSERS.VOICES] CHECK CONSTRAINT [FK_FINGERPRINTS.OS.BROWSERS.VOICES_FINGERPRINTS.OS.BROWSERS]
GO


