USE [YOUR_DATABASE_NAME]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FINGERPRINTS.OS](
	[Fingerprint.OS.ID] [int] IDENTITY(1,1) NOT NULL,
	[Fingerprint.OS] [nvarchar](64) NOT NULL,
 CONSTRAINT [PK_FINGERPRINTS.OS] PRIMARY KEY CLUSTERED 
(
	[Fingerprint.OS.ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


