USE [YOUR_DATABASE_NAME]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FINGERPRINTS](
	[Fingerprint.Audio.ID] [int] NOT NULL,
	[Fingerprint.Cursor.ID] [int] NOT NULL,
	[Fingerprint.GEO.ID] [int] NOT NULL,
	[Fingerprint.Header.ID] [int] NOT NULL,
	[Fingerprint.MediaDevice.ID] [int] NOT NULL,
	[Fingerprint.Misc.ID] [int] NOT NULL,
	[Fingerprint.OS.ID] [int] NOT NULL,
	[Fingerprint.OS.Browser.ID] [int] NOT NULL,
	[Fingerprint.OS.Browser.Voice.ID] [int] NOT NULL,
	[Fingerprint.OS.Font.ID] [int] NOT NULL,
	[Fingerprint.OS.GPU.ID] [int] NOT NULL,
	[Fingerprint.Screen.ID] [int] NOT NULL,
	[Fingerprint.Screen.Window.ID] [int] NOT NULL,
	[Fingerprint.WEBRTC.ID] [int] NOT NULL,
	[Fingerprint.ID] [int] IDENTITY(1,1) NOT NULL,
	[Fingerprint.Added] [datetime2](7) NULL,
 CONSTRAINT [PK_FINGERPRINTS] PRIMARY KEY CLUSTERED 
(
	[Fingerprint.ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FINGERPRINTS] ADD  CONSTRAINT [DF_FINGERPRINTS_Fingerprint.Added]  DEFAULT (getdate()) FOR [Fingerprint.Added]
GO

ALTER TABLE [dbo].[FINGERPRINTS]  WITH CHECK ADD  CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.AUDIOS] FOREIGN KEY([Fingerprint.Audio.ID])
REFERENCES [dbo].[FINGERPRINTS.AUDIOS] ([Fingerprint.Audio.ID])
GO

ALTER TABLE [dbo].[FINGERPRINTS] CHECK CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.AUDIOS]
GO

ALTER TABLE [dbo].[FINGERPRINTS]  WITH CHECK ADD  CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.CURSORS] FOREIGN KEY([Fingerprint.Cursor.ID])
REFERENCES [dbo].[FINGERPRINTS.CURSORS] ([Fingerprint.Cursor.ID])
GO

ALTER TABLE [dbo].[FINGERPRINTS] CHECK CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.CURSORS]
GO

ALTER TABLE [dbo].[FINGERPRINTS]  WITH CHECK ADD  CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.GEOS] FOREIGN KEY([Fingerprint.GEO.ID])
REFERENCES [dbo].[FINGERPRINTS.GEOS] ([Fingerprint.GEO.ID])
GO

ALTER TABLE [dbo].[FINGERPRINTS] CHECK CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.GEOS]
GO

ALTER TABLE [dbo].[FINGERPRINTS]  WITH CHECK ADD  CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.HEADERS] FOREIGN KEY([Fingerprint.Header.ID])
REFERENCES [dbo].[FINGERPRINTS.HEADERS] ([Fingerprint.Header.ID])
GO

ALTER TABLE [dbo].[FINGERPRINTS] CHECK CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.HEADERS]
GO

ALTER TABLE [dbo].[FINGERPRINTS]  WITH CHECK ADD  CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.MEDIADEVICES] FOREIGN KEY([Fingerprint.MediaDevice.ID])
REFERENCES [dbo].[FINGERPRINTS.MEDIADEVICES] ([Fingerprint.MediaDevice.ID])
GO

ALTER TABLE [dbo].[FINGERPRINTS] CHECK CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.MEDIADEVICES]
GO

ALTER TABLE [dbo].[FINGERPRINTS]  WITH CHECK ADD  CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.MISCS] FOREIGN KEY([Fingerprint.Misc.ID])
REFERENCES [dbo].[FINGERPRINTS.MISCS] ([Fingerprint.Misc.ID])
GO

ALTER TABLE [dbo].[FINGERPRINTS] CHECK CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.MISCS]
GO

ALTER TABLE [dbo].[FINGERPRINTS]  WITH CHECK ADD  CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.OS] FOREIGN KEY([Fingerprint.OS.ID])
REFERENCES [dbo].[FINGERPRINTS.OS] ([Fingerprint.OS.ID])
GO

ALTER TABLE [dbo].[FINGERPRINTS] CHECK CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.OS]
GO

ALTER TABLE [dbo].[FINGERPRINTS]  WITH CHECK ADD  CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.OS.BROWSERS] FOREIGN KEY([Fingerprint.OS.Browser.ID])
REFERENCES [dbo].[FINGERPRINTS.OS.BROWSERS] ([Fingerprint.OS.Browser.ID])
GO

ALTER TABLE [dbo].[FINGERPRINTS] CHECK CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.OS.BROWSERS]
GO

ALTER TABLE [dbo].[FINGERPRINTS]  WITH CHECK ADD  CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.OS.BROWSERS.VOICES] FOREIGN KEY([Fingerprint.OS.Browser.Voice.ID])
REFERENCES [dbo].[FINGERPRINTS.OS.BROWSERS.VOICES] ([Fingerprint.OS.Browser.Voice.ID])
GO

ALTER TABLE [dbo].[FINGERPRINTS] CHECK CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.OS.BROWSERS.VOICES]
GO

ALTER TABLE [dbo].[FINGERPRINTS]  WITH CHECK ADD  CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.OS.FONTS] FOREIGN KEY([Fingerprint.OS.Font.ID])
REFERENCES [dbo].[FINGERPRINTS.OS.FONTS] ([Fingerprint.OS.Font.ID])
GO

ALTER TABLE [dbo].[FINGERPRINTS] CHECK CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.OS.FONTS]
GO

ALTER TABLE [dbo].[FINGERPRINTS]  WITH CHECK ADD  CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.OS.GPUS] FOREIGN KEY([Fingerprint.OS.GPU.ID])
REFERENCES [dbo].[FINGERPRINTS.OS.GPUS] ([Fingerprint.OS.GPU.ID])
GO

ALTER TABLE [dbo].[FINGERPRINTS] CHECK CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.OS.GPUS]
GO

ALTER TABLE [dbo].[FINGERPRINTS]  WITH CHECK ADD  CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.SCREENS] FOREIGN KEY([Fingerprint.Screen.ID])
REFERENCES [dbo].[FINGERPRINTS.SCREENS] ([Fingerprint.Screen.ID])
GO

ALTER TABLE [dbo].[FINGERPRINTS] CHECK CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.SCREENS]
GO

ALTER TABLE [dbo].[FINGERPRINTS]  WITH CHECK ADD  CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.SCREENS.WINDOWS] FOREIGN KEY([Fingerprint.Screen.Window.ID])
REFERENCES [dbo].[FINGERPRINTS.SCREENS.WINDOWS] ([Fingerprint.Screen.Window.ID])
GO

ALTER TABLE [dbo].[FINGERPRINTS] CHECK CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.SCREENS.WINDOWS]
GO

ALTER TABLE [dbo].[FINGERPRINTS]  WITH CHECK ADD  CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.WEBRTCS] FOREIGN KEY([Fingerprint.WEBRTC.ID])
REFERENCES [dbo].[FINGERPRINTS.WEBRTCS] ([Fingerprints.WEBRTC.ID])
GO

ALTER TABLE [dbo].[FINGERPRINTS] CHECK CONSTRAINT [FK_FINGERPRINTS_FINGERPRINTS.WEBRTCS]
GO


