USE [YOUR_DATABASE_NAME]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FINGERPRINTS.HEADERS](
	[Fingerprint.Header.ID] [int] IDENTITY(1,1) NOT NULL,
	[Fingerprint.User_Agent] [nvarchar](max) NULL,
	[Fingerprint.Accept_Language] [nvarchar](max) NOT NULL,
	[Fingerprint.Accept_Encoding] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_FINGERPRINTS.HEADERS] PRIMARY KEY CLUSTERED 
(
	[Fingerprint.Header.ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

