USE [YOUR_DATABASE_NAME]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FINGERPRINTS.OS.FONTS](
	[Fingerprint.OS.Browser.ID] [int] NOT NULL,
	[Fingerprint.OS.ID] [int] NOT NULL,
	[Fingerprint.OS.Font.ID] [int] IDENTITY(1,1) NOT NULL,
	[Fingerprint.OS.Font] [nvarchar](192) NOT NULL,
	[Fingerprint.Font.Spacing_seed] [bigint] NULL,
 CONSTRAINT [PK_FINGERPRINTS.OS.FONTS] PRIMARY KEY CLUSTERED 
(
	[Fingerprint.OS.Font.ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FINGERPRINTS.OS.FONTS]  WITH CHECK ADD  CONSTRAINT [FK_FINGERPRINTS.OS.FONTS_FINGERPRINTS.OS] FOREIGN KEY([Fingerprint.OS.Browser.ID])
REFERENCES [dbo].[FINGERPRINTS.OS.BROWSERS] ([Fingerprint.OS.Browser.ID])
GO

ALTER TABLE [dbo].[FINGERPRINTS.OS.FONTS] CHECK CONSTRAINT [FK_FINGERPRINTS.OS.FONTS_FINGERPRINTS.OS]
GO


